Public class BakcupCustomSettingCall{
    /*
    trigger DefaultOrderOwner on Order (before insert) {

    public static final string custmSettngName = 'Default Order Owner';
    
    Default_Order_Owner__c lstSettng = Default_Order_Owner__c.getInstance(custmSettngName);
    for(Order o : trigger.new){
        if(lstSettng.Owner_Id__c != null){
            o.OwnerId = lstSettng.Owner_Id__c;
        }
    } 
}
*/
}